export const DEFAULT_SETTINGS = {
  speed: 1.0,
  nfeSteps: 32,
  removeSilence: true,
  enableChunking: true,
  customSplitWords: [
    "but",
    "however",
    "nevertheless",
    "yet",
    "still",
    "therefore",
    "thus",
    "hence",
    "consequently",
    "moreover",
    "furthermore",
    "additionally",
    "meanwhile",
    "alternatively",
    "otherwise",
    "namely",
    "specifically",
    "for example",
    "such as",
    "in fact",
    "indeed",
    "notably",
    "in contrast",
    "on the other hand",
    "conversely",
    "in conclusion",
    "to summarize",
    "finally",
  ].join(", "),
};
